"""TOTP (RFC 6238) service — secret generation, code verification, and recovery codes.

All TOTP operations are pure functions except ``redeem_recovery_code`` and
``verify_totp_or_recovery``, which accept an ``AsyncSession`` and execute
within the caller's transaction.  No commit is performed here; callers commit
when the full request succeeds.

Never log TOTP secrets or raw recovery codes.
"""

from __future__ import annotations

import hashlib
import hmac
import secrets
import threading
import time

from datetime import UTC, datetime
from typing import Any

import pyotp
import segno

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError, VerifyMismatchError
from itsdangerous import BadSignature, SignatureExpired, TimestampSigner
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from snore.database.models import TotpRecoveryCode

TOTP_PENDING_SALT = "snore-totp-pending-v1"
TOTP_PENDING_MAX_AGE = 300  # seconds
TOTP_ISSUER = "SNORE"
TOTP_PERIOD = 30
RECOVERY_CODE_COUNT = 10

# ---------------------------------------------------------------------------
# Argon2 hasher for recovery codes.
#
# Recovery codes are 40-bit random tokens (secrets.token_hex(5)) generated by
# a CSPRNG, not user-chosen passwords.  Reduced KDF parameters are safe here:
# the full 2**40 search space makes real-time GPU cracking infeasible even at
# these settings, while the fast per-verify time lets us iterate over all ≤10
# unredeemed codes without blocking the event loop for a noticeable interval.
# User passwords use the default hasher (time_cost=3, memory_cost=65536) in
# snore.auth.passwords for their much weaker, user-chosen entropy.
# ---------------------------------------------------------------------------
_recovery_hasher = PasswordHasher(time_cost=1, memory_cost=8192, parallelism=1)

# ---------------------------------------------------------------------------
# Pending-token single-use registry
#
# Prevents replay of the 5-minute TOTP pending token within its validity window.
# Each token is stored by its sha256 digest mapped to a monotonic expiry.
# Pruned on each access; bounded to ``_TOKEN_REGISTRY_MAX`` entries (when full
# the entry that expires soonest is evicted, corresponding to the oldest token).
# Single-process deployment — no persistence or cross-worker coordination needed.
# ---------------------------------------------------------------------------
_TOKEN_REGISTRY_MAX = 1000
_consumed_tokens: dict[str, float] = {}  # sha256hex(token) → monotonic expiry
_token_registry_lock = threading.Lock()


def generate_totp_secret() -> str:
    """Generate a random Base32 TOTP secret via pyotp."""
    return pyotp.random_base32()


def build_provisioning_uri(secret: str, email: str) -> str:
    """Build an ``otpauth://`` URI for authenticator app enrollment.

    Emits SHA1 / 6-digit / 30-second defaults via pyotp so all standard
    authenticator apps (Google Authenticator, Authy, 1Password, etc.) parse it
    without extra configuration.
    """
    return pyotp.TOTP(secret).provisioning_uri(name=email, issuer_name=TOTP_ISSUER)


def build_qr_data_uri(uri: str) -> str:
    """Return a ``data:image/svg+xml`` URI for the provisioning URI QR code.

    The returned value can be used directly as an ``<img src>`` attribute —
    no external server request is needed.
    """
    return segno.make(uri, error="m").svg_data_uri()


def verify_totp_code(
    secret: str, code: str, last_used_step: int | None
) -> tuple[bool, int]:
    """Verify a TOTP code against *secret* with replay protection.

    Accepts codes from the previous, current, or next 30-second window to
    tolerate reasonable clock skew between client and server.  The matched
    time-step is returned so the caller can persist it for replay prevention.

    All three offsets are always scanned (no early break) to keep timing
    uniform regardless of which window the code falls in.

    Args:
        secret:          Base32 TOTP secret.
        code:            6-digit string supplied by the user.
        last_used_step:  Most recently verified time-step stored in the DB, or
                         ``None`` for the first verification.

    Returns:
        ``(True, matched_step)`` on success; ``(False, current_step)`` on
        mismatch or replay.
    """
    now = time.time()
    current_step = int(now // TOTP_PERIOD)
    totp = pyotp.TOTP(secret)

    matched_step: int | None = None
    for offset in (-1, 0, 1):
        expected = totp.at(int(now) + offset * TOTP_PERIOD)
        if hmac.compare_digest(expected, code):
            matched_step = current_step + offset

    if matched_step is None:
        return False, current_step

    # Replay guard: reject a step that was already accepted.
    if matched_step <= (last_used_step if last_used_step is not None else -1):
        return False, current_step

    return True, matched_step


def generate_recovery_codes(count: int = RECOVERY_CODE_COUNT) -> list[str]:
    """Generate *count* one-time recovery codes (10 lowercase hex chars each)."""
    return [secrets.token_hex(5) for _ in range(count)]


def hash_recovery_code(raw: str) -> str:
    """Return an argon2-encoded hash of a raw recovery code.

    Reduced KDF parameters are safe for CSPRNG-generated 40-bit tokens; see
    ``_recovery_hasher`` for the rationale.
    """
    return _recovery_hasher.hash(raw)


async def redeem_recovery_code(db: AsyncSession, user_id: int, raw: str) -> bool:
    """Mark a recovery code as used if it exists and is unused for *user_id*.

    Fetches all unredeemed codes for the user (≤10 by construction) and
    verifies each with argon2, short-circuiting on the first match.  Lookup
    by hash equality is not possible with argon2 because each hash embeds a
    unique random salt.

    Runs inside the caller's request transaction — no commit is performed here.

    Returns:
        ``True`` if the code was valid and has been marked used; ``False`` if
        the code does not exist, belongs to a different user, or was already used.
    """
    result = await db.execute(
        select(TotpRecoveryCode).where(
            TotpRecoveryCode.user_id == user_id,
            TotpRecoveryCode.used_at.is_(None),
        )
    )
    rows = result.scalars().all()
    for row in rows:
        try:
            _recovery_hasher.verify(row.code_hash, raw)
            row.used_at = datetime.now(UTC)
            return True
        except (VerifyMismatchError, VerificationError, InvalidHashError):
            continue
    return False


def is_totp_code(code: str) -> bool:
    """Return True if *code* is exactly 6 ASCII decimal digits."""
    return len(code) == 6 and code.isascii() and code.isdigit()


def is_recovery_code(code: str) -> bool:
    """Return True if *code* is exactly 10 lowercase hexadecimal characters."""
    return (
        len(code) == 10
        and code.isascii()
        and all(c in "0123456789abcdef" for c in code)
    )


def _make_pending_signer(secret: str) -> TimestampSigner:
    return TimestampSigner(secret, salt=TOTP_PENDING_SALT)


def encode_totp_pending_token(secret: str, user_id: int) -> str:
    """Produce a time-limited signed token embedding *user_id* and a random nonce.

    The payload is ``"{user_id}:{nonce}"`` where *nonce* is 8 random hex bytes.
    The nonce makes each token globally unique even when the same user completes
    two password-auth flows within the same second (TimestampSigner has 1-second
    granularity), preventing the consumed-token registry from falsely rejecting a
    legitimately re-issued token.

    Args:
        secret:   SNORE session secret (``AppConfig.session_secret``).
        user_id:  ID of the user completing enrollment.

    Returns:
        An opaque URL-safe string valid for ``TOTP_PENDING_MAX_AGE`` seconds.
    """
    payload = f"{user_id}:{secrets.token_hex(8)}"
    return _make_pending_signer(secret).sign(payload).decode()


def decode_totp_pending_token(secret: str, token: str) -> int | None:
    """Validate and decode a pending TOTP token, returning the user ID.

    The signed payload is ``"{user_id}:{nonce}"``; only the user ID is returned.
    The nonce is discarded after signature verification.

    Args:
        secret:  SNORE session secret used to sign the token.
        token:   Token produced by ``encode_totp_pending_token``.

    Returns:
        The embedded user ID as an ``int`` if the token is valid and unexpired;
        ``None`` on ``BadSignature``, ``SignatureExpired``, or ``ValueError``.
    """
    try:
        raw = (
            _make_pending_signer(secret)
            .unsign(token.encode(), max_age=TOTP_PENDING_MAX_AGE)
            .decode()
        )
        user_id_str, _, _ = raw.partition(":")
        return int(user_id_str)
    except (BadSignature, SignatureExpired, ValueError):
        return None


def _prune_token_registry(now: float) -> None:
    """Remove expired entries from the consumed-token registry.

    Caller must hold ``_token_registry_lock``.
    """
    expired = [k for k, exp in _consumed_tokens.items() if exp <= now]
    for k in expired:
        del _consumed_tokens[k]


def is_token_consumed(raw_token: str) -> bool:
    """Return True if *raw_token* has already been used for a TOTP login.

    Prunes expired entries on each call so the registry self-cleans without
    a background task.
    """
    key = hashlib.sha256(raw_token.encode()).hexdigest()
    now = time.monotonic()
    with _token_registry_lock:
        _prune_token_registry(now)
        return key in _consumed_tokens


def consume_pending_token(raw_token: str) -> None:
    """Mark *raw_token* as consumed; subsequent ``is_token_consumed`` calls return True.

    Call only after a successful TOTP second-factor authentication.  The entry
    expires after ``TOTP_PENDING_MAX_AGE`` seconds — the same window as the
    token itself — so stale entries are pruned automatically.
    """
    key = hashlib.sha256(raw_token.encode()).hexdigest()
    now = time.monotonic()
    expiry = now + TOTP_PENDING_MAX_AGE
    with _token_registry_lock:
        _prune_token_registry(now)
        if len(_consumed_tokens) >= _TOKEN_REGISTRY_MAX:
            # Evict the token that expires soonest (the oldest issued token).
            oldest = min(_consumed_tokens, key=lambda k: _consumed_tokens[k])
            del _consumed_tokens[oldest]
        _consumed_tokens[key] = expiry


async def verify_totp_or_recovery(
    db: AsyncSession,
    user: Any,
    code: str,
) -> tuple[bool, int | None]:
    """Dispatch TOTP code or recovery-code verification for *user*.

    Returns the matched TOTP time-step so the caller can persist replay-
    prevention state when it is non-None.  The code should be stripped by
    the caller before passing.

    Args:
        db:   Async session within the caller's transaction.
        user: ORM User row with ``totp_secret``, ``totp_last_used_step``, ``id``.
        code: Pre-stripped code string from the request.

    Returns:
        ``(True, step)`` on TOTP match (step is the matched time-step);
        ``(True, None)`` on recovery-code match;
        ``(False, None)`` on any mismatch, replay, or unrecognised format.
    """
    if is_totp_code(code):
        ok, step = verify_totp_code(user.totp_secret, code, user.totp_last_used_step)
        return (True, step) if ok else (False, None)
    if is_recovery_code(code.lower()):
        ok = await redeem_recovery_code(db, user.id, code.lower())
        return (True, None) if ok else (False, None)
    return False, None
