"""OSCAR channel ID to SNORE unified model mappings."""

from snore.constants import (
    CPAP_CLEAR_AIRWAY,
    CPAP_CSR,
    CPAP_EPAP,
    CPAP_FLOW_LIMIT,
    CPAP_FLOW_RATE,
    CPAP_HYPOPNEA,
    CPAP_LEAK,
    CPAP_MASK_PRESSURE,
    CPAP_MINUTE_VENT,
    CPAP_OBSTRUCTIVE,
    CPAP_PERIODIC_BREATHING,
    CPAP_PRESSURE,
    CPAP_RERA,
    CPAP_RESPRATE,
    CPAP_TIDAL_VOLUME,
    OXI_PULSE,
    OXI_SPO2,
    UNIT_BPM,
    UNIT_FLOW,
    UNIT_ML,
    UNIT_PERCENT,
    UNIT_PRESSURE_DISPLAY,
)
from snore.parsers.unified import RespiratoryEventType, WaveformType

__all__ = [
    "OSCAR_EVENT_TYPE_MAP",
    "OSCAR_WAVEFORM_TYPE_MAP",
    "OSCAR_WAVEFORM_UNITS",
    "OSCAR_EVENT_CHANNEL_IDS",
    "OSCAR_WAVEFORM_CHANNEL_IDS",
]

OSCAR_EVENT_TYPE_MAP: dict[int, RespiratoryEventType] = {
    CPAP_OBSTRUCTIVE: RespiratoryEventType.OBSTRUCTIVE_APNEA,
    CPAP_HYPOPNEA: RespiratoryEventType.HYPOPNEA,
    CPAP_CLEAR_AIRWAY: RespiratoryEventType.CENTRAL_APNEA,
    CPAP_RERA: RespiratoryEventType.RERA,
    CPAP_FLOW_LIMIT: RespiratoryEventType.FLOW_LIMITATION,
    CPAP_CSR: RespiratoryEventType.PERIODIC_BREATHING,
    CPAP_PERIODIC_BREATHING: RespiratoryEventType.PERIODIC_BREATHING,
}

OSCAR_WAVEFORM_TYPE_MAP: dict[int, WaveformType] = {
    CPAP_FLOW_RATE: WaveformType.FLOW_RATE,
    CPAP_PRESSURE: WaveformType.THERAPY_PRESSURE,
    CPAP_MASK_PRESSURE: WaveformType.MASK_PRESSURE,
    CPAP_EPAP: WaveformType.EPAP,
    CPAP_LEAK: WaveformType.LEAK_RATE,
    CPAP_RESPRATE: WaveformType.RESPIRATORY_RATE,
    CPAP_TIDAL_VOLUME: WaveformType.TIDAL_VOLUME,
    CPAP_MINUTE_VENT: WaveformType.MINUTE_VENTILATION,
    OXI_SPO2: WaveformType.SPO2,
    OXI_PULSE: WaveformType.PULSE,
}

OSCAR_WAVEFORM_UNITS: dict[int, str] = {
    CPAP_FLOW_RATE: UNIT_FLOW,
    CPAP_PRESSURE: UNIT_PRESSURE_DISPLAY,
    CPAP_MASK_PRESSURE: UNIT_PRESSURE_DISPLAY,
    CPAP_EPAP: UNIT_PRESSURE_DISPLAY,
    CPAP_LEAK: UNIT_FLOW,
    CPAP_RESPRATE: UNIT_BPM,
    CPAP_TIDAL_VOLUME: UNIT_ML,
    CPAP_MINUTE_VENT: UNIT_FLOW,
    OXI_SPO2: UNIT_PERCENT,
    OXI_PULSE: UNIT_BPM,
}

OSCAR_EVENT_CHANNEL_IDS: set[int] = set(OSCAR_EVENT_TYPE_MAP.keys())

OSCAR_WAVEFORM_CHANNEL_IDS: set[int] = set(OSCAR_WAVEFORM_TYPE_MAP.keys())
