/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/v1/analysis': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /** Delete Analysis */
        delete: operations['delete_analysis_api_v1_analysis_delete']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/analysis/delete-preview': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Analysis Delete Preview */
        get: operations['get_analysis_delete_preview_api_v1_analysis_delete_preview_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/analysis/sessions': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List Analysis Sessions */
        get: operations['list_analysis_sessions_api_v1_analysis_sessions_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/days/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List Days */
        get: operations['list_days_api_v1_days__get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/days/{day_date}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Day */
        get: operations['get_day_api_v1_days__day_date__get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/devices/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List Devices */
        get: operations['list_devices_api_v1_devices__get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/rx/compare': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Compare Rx */
        get: operations['compare_rx_api_v1_rx_compare_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/rx/current': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Rx Current */
        get: operations['get_rx_current_api_v1_rx_current_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/rx/history': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Rx History */
        get: operations['get_rx_history_api_v1_rx_history_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List Sessions */
        get: operations['list_sessions_api_v1_sessions__get']
        put?: never
        post?: never
        /** Delete Sessions */
        delete: operations['delete_sessions_api_v1_sessions__delete']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/{session_id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Session */
        get: operations['get_session_api_v1_sessions__session_id__get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        /** Update Session */
        patch: operations['update_session_api_v1_sessions__session_id__patch']
        trace?: never
    }
    '/api/v1/sessions/{session_id}/analysis': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Analysis */
        get: operations['get_analysis_api_v1_sessions__session_id__analysis_get']
        put?: never
        /** Run Analysis */
        post: operations['run_analysis_api_v1_sessions__session_id__analysis_post']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/{session_id}/delete-preview': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Delete Preview */
        get: operations['get_delete_preview_api_v1_sessions__session_id__delete_preview_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/{session_id}/events': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List Events */
        get: operations['list_events_api_v1_sessions__session_id__events_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/{session_id}/events/match': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Match Events */
        get: operations['match_events_api_v1_sessions__session_id__events_match_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/{session_id}/waveforms': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List Waveforms */
        get: operations['list_waveforms_api_v1_sessions__session_id__waveforms_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/sessions/{session_id}/waveforms/{waveform_type}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Waveform */
        get: operations['get_waveform_api_v1_sessions__session_id__waveforms__waveform_type__get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/stats/periods': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Periods */
        get: operations['get_periods_api_v1_stats_periods_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/stats/records': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Records */
        get: operations['get_records_api_v1_stats_records_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/stats/summary': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Summary */
        get: operations['get_summary_api_v1_stats_summary_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/v1/stats/trends': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Trends */
        get: operations['get_trends_api_v1_stats_trends_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        /**
         * AnalysisDeletePreview
         * @description Preview of analysis data to be deleted.
         */
        AnalysisDeletePreview: {
            /** Patterns Count */
            patterns_count: number
            /** Records To Delete */
            records_to_delete: number
            /** Session Details */
            session_details?: components['schemas']['AnalysisSessionDetail'][]
            /** Sessions With Analysis */
            sessions_with_analysis: number
            /** Total Analysis Records */
            total_analysis_records: number
        }
        /** AnalysisDeleteRequest */
        AnalysisDeleteRequest: {
            /**
             * All Versions
             * @default false
             */
            all_versions: boolean
            /** Session Ids */
            session_ids?: number[]
        }
        /**
         * AnalysisListItem
         * @description Session with analysis status for listing.
         */
        AnalysisListItem: {
            /** Analysis Id */
            analysis_id?: number | null
            /** Duration Hours */
            duration_hours?: number | null
            /** Has Analysis */
            has_analysis: boolean
            /**
             * Session Date
             * Format: date
             */
            session_date: string
            /** Session Id */
            session_id: number
        }
        /** AnalysisRunRequest */
        AnalysisRunRequest: {
            /** Modes */
            modes?: string[]
            /**
             * Store Results
             * @default true
             */
            store_results: boolean
        }
        /**
         * AnalysisSessionDetail
         * @description Session detail for analysis deletion preview.
         */
        AnalysisSessionDetail: {
            /** Id */
            id: number
            /** Manufacturer */
            manufacturer?: string | null
            /** Model */
            model?: string | null
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string
            /** Version Count */
            version_count: number
        }
        /**
         * DayDetail
         * @description Full detail of a therapy day including per-metric stats.
         */
        DayDetail: {
            /** Ahi */
            ahi?: number | null
            /** Avg Leak */
            avg_leak?: number | null
            /** Avg Pressure */
            avg_pressure?: number | null
            /** Avg Spo2 */
            avg_spo2?: number | null
            /** Cai */
            cai?: number | null
            /**
             * Date
             * Format: date
             */
            date: string
            /** Device Id */
            device_id: number
            /** Hi */
            hi?: number | null
            /** Oai */
            oai?: number | null
            /** Session Count */
            session_count: number
            /** Session Ids */
            session_ids?: number[]
            /** Total Therapy Hours */
            total_therapy_hours?: number | null
        }
        /**
         * DayListItem
         * @description Summary of a single therapy day.
         */
        DayListItem: {
            /** Ahi */
            ahi?: number | null
            /**
             * Date
             * Format: date
             */
            date: string
            /** Device Id */
            device_id: number
            /** Session Count */
            session_count: number
            /** Total Therapy Hours */
            total_therapy_hours?: number | null
        }
        /**
         * DeletePreview
         * @description Preview of sessions and related data to be deleted.
         */
        DeletePreview: {
            /**
             * Event Count
             * @description Total events to be deleted
             */
            event_count: number
            /**
             * Sessions
             * @description Sessions to be deleted
             */
            sessions: components['schemas']['SessionListItem'][]
            /**
             * Stats Count
             * @description Total statistics records to be deleted
             */
            stats_count: number
            /**
             * Waveform Count
             * @description Total waveform records to be deleted
             */
            waveform_count: number
        }
        /**
         * DeviceInfo
         * @description Device information for listing.
         */
        DeviceInfo: {
            /** Id */
            id: number
            /** Manufacturer */
            manufacturer: string
            /** Model */
            model: string
            /** Serial Number */
            serial_number: string
        }
        /** EventItem */
        EventItem: {
            /** Duration Seconds */
            duration_seconds: number
            /** Event Type */
            event_type: string
            /** Id */
            id: number
            /** Offset Seconds */
            offset_seconds: number
            /** Start Time */
            start_time: number
        }
        /**
         * EventMatchResult
         * @description Result of matching machine vs programmatic events.
         */
        EventMatchResult: {
            /** False Negatives */
            false_negatives: number
            /** False Positives */
            false_positives: number
            /** Machine Count */
            machine_count: number
            /** Matched */
            matched: number
            /** Programmatic Count */
            programmatic_count: number
        }
        /**
         * EventTypeCount
         * @description Event type with count and percentage.
         */
        EventTypeCount: {
            /** Count */
            count: number
            /** Event Type */
            event_type: string
            /** Percentage */
            percentage: number
        }
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components['schemas']['ValidationError'][]
        }
        /** PaginatedResponse[AnalysisListItem] */
        PaginatedResponse_AnalysisListItem_: {
            /** Items */
            items: components['schemas']['AnalysisListItem'][]
            /** Limit */
            limit: number
            /** Offset */
            offset: number
            /** Total */
            total: number
        }
        /** PaginatedResponse[DayListItem] */
        PaginatedResponse_DayListItem_: {
            /** Items */
            items: components['schemas']['DayListItem'][]
            /** Limit */
            limit: number
            /** Offset */
            offset: number
            /** Total */
            total: number
        }
        /** PaginatedResponse[SessionListItem] */
        PaginatedResponse_SessionListItem_: {
            /** Items */
            items: components['schemas']['SessionListItem'][]
            /** Limit */
            limit: number
            /** Offset */
            offset: number
            /** Total */
            total: number
        }
        /**
         * PeriodStatistics
         * @description Statistics for a time period (week, month, year).
         * @example {
         *       "avg_ahi": 2.8,
         *       "avg_hours_per_day": 7.2,
         *       "avg_leak": 9.2,
         *       "avg_pressure": 10.5,
         *       "avg_spo2": 96.2,
         *       "days_in_period": 31,
         *       "days_used": 29,
         *       "median_ahi": 2.3,
         *       "min_spo2": 89,
         *       "period_end": "2024-01-31",
         *       "period_start": "2024-01-01",
         *       "period_type": "monthly"
         *     }
         */
        PeriodStatistics: {
            /**
             * Avg Ahi
             * @description Average AHI
             */
            avg_ahi?: number | null
            /**
             * Avg Hours Per Day
             * @description Average hours per day used
             */
            avg_hours_per_day?: number | null
            /**
             * Avg Leak
             * @description Average leak rate (L/min)
             */
            avg_leak?: number | null
            /**
             * Avg Pressure
             * @description Average pressure (cmH₂O)
             */
            avg_pressure?: number | null
            /**
             * Avg Spo2
             * @description Average SpO₂ (%)
             */
            avg_spo2?: number | null
            /**
             * Days In Period
             * @description Total days in period
             * @default 0
             */
            days_in_period: number
            /**
             * Days Used
             * @description Number of days with therapy
             * @default 0
             */
            days_used: number
            /**
             * Median Ahi
             * @description Median AHI
             */
            median_ahi?: number | null
            /**
             * Min Spo2
             * @description Minimum SpO₂ (%)
             */
            min_spo2?: number | null
            /**
             * Period End
             * Format: date
             */
            period_end: string
            /**
             * Period Start
             * Format: date
             */
            period_start: string
            /**
             * Period Type
             * @description Type: daily, weekly, monthly, yearly
             */
            period_type: string
        }
        /**
         * RxComparisonResponse
         * @description RX period comparison result with best/worst indices.
         */
        RxComparisonResponse: {
            /** Best Index */
            best_index?: number | null
            /** Periods */
            periods: components['schemas']['RxPeriodResponse'][]
            /** Worst Index */
            worst_index?: number | null
        }
        /**
         * RxPeriodResponse
         * @description Single therapy prescription period with aggregated stats.
         */
        RxPeriodResponse: {
            /** Avg Ahi */
            avg_ahi?: number | null
            /** Avg Hours */
            avg_hours?: number | null
            /** Avg Leak */
            avg_leak?: number | null
            /** Days Count */
            days_count: number
            /**
             * End Date
             * Format: date
             */
            end_date: string
            /** Median Ahi */
            median_ahi?: number | null
            /** Settings */
            settings: {
                [key: string]: string
            }
            /**
             * Start Date
             * Format: date
             */
            start_date: string
            /**
             * Total Hours
             * @default 0
             */
            total_hours: number
        }
        /** SessionDeleteRequest */
        SessionDeleteRequest: {
            /** Session Ids */
            session_ids: number[]
        }
        /**
         * SessionDetail
         * @description Detailed view of a single session with all metadata.
         */
        SessionDetail: {
            /** Device Manufacturer */
            device_manufacturer: string | null
            /** Device Model */
            device_model: string | null
            /** Device Serial */
            device_serial: string | null
            /** Device Session Id */
            device_session_id: string
            /** Duration Hours */
            duration_hours: number
            /** Duration Seconds */
            duration_seconds: number
            /** Enabled */
            enabled: boolean
            /**
             * End Time
             * Format: date-time
             */
            end_time: string
            /** Event Count */
            event_count: number
            /** Has Event Data */
            has_event_data: boolean
            /** Has Statistics */
            has_statistics: boolean
            /** Id */
            id: number
            /** Settings */
            settings?: components['schemas']['SessionSetting'][] | null
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string
            statistics?: components['schemas']['SessionStatistics'] | null
            /** Therapy Mode */
            therapy_mode: string | null
            /** Waveform Count */
            waveform_count: number
            /** Waveform Types */
            waveform_types: string[]
        }
        /** SessionEnabledRequest */
        SessionEnabledRequest: {
            /** Enabled */
            enabled: boolean
        }
        /**
         * SessionListItem
         * @description Single session item in a list view.
         */
        SessionListItem: {
            /**
             * Ahi
             * @description Apnea-Hypopnea Index
             */
            ahi?: number | null
            /**
             * Duration Hours
             * @description Session duration in hours
             */
            duration_hours: number
            /**
             * Enabled
             * @description Whether session is enabled for stats
             */
            enabled: boolean
            /**
             * Id
             * @description Session database ID
             */
            id: number
            /**
             * Manufacturer
             * @description Device manufacturer
             */
            manufacturer: string
            /**
             * Model
             * @description Device model
             */
            model: string
            /**
             * Serial Number
             * @description Device serial number
             */
            serial_number: string
            /**
             * Start Time
             * Format: date-time
             * @description Session start timestamp
             */
            start_time: string
        }
        /**
         * SessionSetting
         * @description Single setting key-value pair for a session.
         */
        SessionSetting: {
            /**
             * Key
             * @description Setting key
             */
            key: string
            /**
             * Value
             * @description Setting value
             */
            value?: string | null
        }
        /**
         * SessionStatistics
         * @description Statistics for a single session (from Statistics table).
         */
        SessionStatistics: {
            /** Ahi */
            ahi?: number | null
            /** Cai */
            cai?: number | null
            /** Central Apneas */
            central_apneas?: number | null
            /** Epap 95Th */
            epap_95th?: number | null
            /** Epap Max */
            epap_max?: number | null
            /** Epap Mean */
            epap_mean?: number | null
            /** Epap Min */
            epap_min?: number | null
            /** Flow Limitations */
            flow_limitations?: number | null
            /** Hi */
            hi?: number | null
            /** Hypopneas */
            hypopneas?: number | null
            /** Leak 95Th */
            leak_95th?: number | null
            /** Leak Mean */
            leak_mean?: number | null
            /** Leak Percentile 70 */
            leak_percentile_70?: number | null
            /** Minute Ventilation Mean */
            minute_ventilation_mean?: number | null
            /** Mixed Apneas */
            mixed_apneas?: number | null
            /** Oai */
            oai?: number | null
            /** Obstructive Apneas */
            obstructive_apneas?: number | null
            /** Pressure 95Th */
            pressure_95th?: number | null
            /** Pressure Max */
            pressure_max?: number | null
            /** Pressure Mean */
            pressure_mean?: number | null
            /** Pressure Min */
            pressure_min?: number | null
            /** Pulse Max */
            pulse_max?: number | null
            /** Pulse Mean */
            pulse_mean?: number | null
            /** Pulse Min */
            pulse_min?: number | null
            /** Rei */
            rei?: number | null
            /** Reras */
            reras?: number | null
            /** Respiratory Rate Mean */
            respiratory_rate_mean?: number | null
            /** Spo2 Mean */
            spo2_mean?: number | null
            /** Spo2 Min */
            spo2_min?: number | null
            /** Spo2 Time Below 90 */
            spo2_time_below_90?: number | null
            /** Tidal Volume Mean */
            tidal_volume_mean?: number | null
            /** Usage Hours */
            usage_hours?: number | null
        }
        /**
         * TherapySummary
         * @description Aggregated therapy statistics summary.
         */
        TherapySummary: {
            /** Avg Ahi */
            avg_ahi?: number | null
            /** Avg Epap */
            avg_epap?: number | null
            /** Avg Hours */
            avg_hours: number
            /** Avg Leak */
            avg_leak?: number | null
            /** Avg Minute Ventilation */
            avg_minute_ventilation?: number | null
            /** Avg Pressure */
            avg_pressure?: number | null
            /** Avg Pulse */
            avg_pulse?: number | null
            /** Avg Rei */
            avg_rei?: number | null
            /** Avg Respiratory Rate */
            avg_respiratory_rate?: number | null
            /** Avg Spo2 */
            avg_spo2?: number | null
            /** Avg Tidal Volume */
            avg_tidal_volume?: number | null
            /** Days Since Last */
            days_since_last: number
            /** Days With Data */
            days_with_data: number
            /**
             * Effectiveness
             * @default unknown
             */
            effectiveness: string
            /** Event Counts */
            event_counts?: components['schemas']['EventTypeCount'][]
            /**
             * First Date
             * Format: date
             */
            first_date: string
            /**
             * Last Date
             * Format: date
             */
            last_date: string
            /** Max Pressure */
            max_pressure?: number | null
            /** Min Pressure */
            min_pressure?: number | null
            /** Min Spo2 */
            min_spo2?: number | null
            /** Total Hours */
            total_hours: number
            /**
             * Total Spo2 Time Below 90
             * @default 0
             */
            total_spo2_time_below_90: number
        }
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>
            /** Input */
            input?: unknown
            /** Location */
            loc: (string | number)[]
            /** Message */
            msg: string
            /** Error Type */
            type: string
        }
        /** WaveformDataResponse */
        WaveformDataResponse: {
            /** Downsampled */
            downsampled: boolean
            /** Returned Samples */
            returned_samples: number
            /** Sample Rate */
            sample_rate: number
            /** Timestamps */
            timestamps: number[]
            /** Total Samples */
            total_samples: number
            /** Unit */
            unit: string
            /** Values */
            values: number[]
        }
        /**
         * WaveformInfo
         * @description Waveform metadata for listing.
         */
        WaveformInfo: {
            /** Duration Hours */
            duration_hours: number
            /** Sample Count */
            sample_count: number
            /** Sample Rate */
            sample_rate: number
            /** Unit */
            unit?: string | null
            /** Waveform Type */
            waveform_type: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    delete_analysis_api_v1_analysis_delete: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['AnalysisDeleteRequest']
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        [key: string]: number
                    }
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_analysis_delete_preview_api_v1_analysis_delete_preview_get: {
        parameters: {
            query?: {
                session_ids?: number[]
                all_versions?: boolean
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['AnalysisDeletePreview']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    list_analysis_sessions_api_v1_analysis_sessions_get: {
        parameters: {
            query?: {
                analyzed_only?: boolean
                sort_by?: string
                limit?: number
                offset?: number
                from_date?: string | null
                to_date?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['PaginatedResponse_AnalysisListItem_']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    list_days_api_v1_days__get: {
        parameters: {
            query?: {
                device_id?: number | null
                limit?: number
                offset?: number
                from_date?: string | null
                to_date?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['PaginatedResponse_DayListItem_']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_day_api_v1_days__day_date__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                day_date: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['DayDetail']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    list_devices_api_v1_devices__get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['DeviceInfo'][]
                }
            }
        }
    }
    compare_rx_api_v1_rx_compare_get: {
        parameters: {
            query?: {
                min_days?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['RxComparisonResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_rx_current_api_v1_rx_current_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['RxPeriodResponse']
                }
            }
            /** @description No RX data available */
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    get_rx_history_api_v1_rx_history_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['RxPeriodResponse'][]
                }
            }
        }
    }
    list_sessions_api_v1_sessions__get: {
        parameters: {
            query?: {
                device?: string | null
                sort_by?: 'date-asc' | 'date-desc' | 'session-id' | 'duration'
                include_disabled?: boolean
                limit?: number
                offset?: number
                from_date?: string | null
                to_date?: string | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['PaginatedResponse_SessionListItem_']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    delete_sessions_api_v1_sessions__delete: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['SessionDeleteRequest']
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        [key: string]: unknown
                    }
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: {
                include_settings?: boolean
            }
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['SessionDetail']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    update_session_api_v1_sessions__session_id__patch: {
        parameters: {
            query?: never
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['SessionEnabledRequest']
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['SessionDetail']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_analysis_api_v1_sessions__session_id__analysis_get: {
        parameters: {
            query?: never
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    run_analysis_api_v1_sessions__session_id__analysis_post: {
        parameters: {
            query?: never
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['AnalysisRunRequest']
            }
        }
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_delete_preview_api_v1_sessions__session_id__delete_preview_get: {
        parameters: {
            query?: never
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['DeletePreview']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    list_events_api_v1_sessions__session_id__events_get: {
        parameters: {
            query?: {
                event_type?: string | null
            }
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['EventItem'][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    match_events_api_v1_sessions__session_id__events_match_get: {
        parameters: {
            query?: {
                mode?: string
            }
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['EventMatchResult']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    list_waveforms_api_v1_sessions__session_id__waveforms_get: {
        parameters: {
            query?: never
            header?: never
            path: {
                session_id: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['WaveformInfo'][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_waveform_api_v1_sessions__session_id__waveforms__waveform_type__get: {
        parameters: {
            query?: {
                max_points?: number
                start_seconds?: number | null
                end_seconds?: number | null
            }
            header?: never
            path: {
                session_id: number
                waveform_type:
                    | 'flow'
                    | 'pressure'
                    | 'therapy_pressure'
                    | 'epap'
                    | 'leak'
                    | 'mv'
                    | 'rr'
                    | 'tv'
                    | 'spo2'
                    | 'pulse'
                    | 'fl'
                    | 'snore'
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['WaveformDataResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_periods_api_v1_stats_periods_get: {
        parameters: {
            query?: {
                period_type?: 'week' | 'month' | '6month' | 'year'
                days_limit?: number | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['PeriodStatistics'][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_records_api_v1_stats_records_get: {
        parameters: {
            query?: {
                days_limit?: number | null
                top_n?: number
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_summary_api_v1_stats_summary_get: {
        parameters: {
            query?: {
                days_limit?: number | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['TherapySummary']
                }
            }
            /** @description No therapy data available */
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_trends_api_v1_stats_trends_get: {
        parameters: {
            query?: {
                period_type?: 'week' | 'month' | '6month' | 'year'
                days_limit?: number | null
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': unknown
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
}
